kind: Deployment
apiVersion: apps/v1
metadata:
  # 名字
  name: tianxuan-gateway
  # 配置namespace
  namespace: tianxuan-common-service
  labels:
    app: tianxuan-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tianxuan-gateway
  template:
    metadata:
      labels:
        app: tianxuan-gateway
    spec:
      containers:
        # 定义容器名称
        - name: container-tianxuan-gateway
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$SERVICE_NAME:$PROJECT_VERSION
          ports:
            - name: tcp-11031
              containerPort: 11031
              protocol: TCP
          resources:
            limits:
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

kind: Service
apiVersion: v1
metadata:
  name: tianxuan-gateway
  namespace: tianxuan-common-service
  labels:
    app: tianxuan-gateway
spec:
  ports:
    - name: tcp-11031
      protocol: TCP
      port: 11031
      targetPort: 11031
      nodePort: 31031
  selector:
    app: tianxuan-gateway
  type: NodePort
  sessionAffinity: None