server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
  port: 7001
spring:
  profiles:
    active: dev

# 配置日志级别
logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml